### ISSUE TITLE
subscribers get their own messages if they publish

### ISSUE THREAD

**Issue by jvsteiner** [libp2p/go-floodsub#65]
I've noticed that if a pubsub is subscribed to a topic, and it also publishes on that topic, that it will receive it's own message.  Is this intended behavior?

If so, I'd be interested to understand the thinking.  In my usage so far, I have had to explicitly tag publications, so I can ignore messages from my own node.  It's not a huge burden, but it did lead to some unexpected issues.

**Comment by Stebalien** [comment]
Yes, this is intended. As publishing and subscribing are independent, one might have a situation with two applications that happen to be running on the same machine where one publishes and the other subscribes. If we filtered our own messages, the subscriber would never see the message.

We could change this by publishing through the `Subscription` object but we'll have to think about that. Given that it's easier for the pubsub library to determine where the message came from than it is for the application, we should probably consider doing this (maybe make it a subscription option). Thoughts @vyzo? My primary worry here is increasing the API of the `Subscription` object by adding a `Publish` method.

Personally, I prefer to write applications such that they take advantage of this feedback. Instead of updating my application state when an event happens, I immediately publish the event to the pubsub system and then allow my own internal subscriber to update the application state. However, this isn't always possible or desirable.

**Comment by vyzo** [comment]
It's a little like the behaviour of multicast loopback in IP multicast. Both behaviours are useful, and in a multi-tenant environment the sane default is to deliver loopback messages.

We can certainly add an option to the subscription to not deliver our own messages, because we are well positioned to do so and it will simplify single-tenant applications.

**Comment by jvsteiner** [comment]
my outside view is that an option is a nice way to do this - it clarifies that the behavior is intended, and offers a way to turn it off cleanly if it's not desired.  Like I say, it's trivial to handle it in application code, but you have to know to expect it.  Depending on the developers frame of mind, that might not be a given, and the existence of an option makes it explicit.

**Comment by jvsteiner** [comment]
BTW other parts of my code _do_ rely on this: "Instead of updating my application state when an event happens..."  - that's a solid point.  Mainly so far, it's the discovery type functionality, where I don't need to discover myself, that I've needed to avoid self messaging.

**Comment by Stebalien** [comment]
FYI: Messages *do* include a From field (specifying the origin of the message).

**Comment by jvsteiner** [comment]
fair point - I missed this possibility.  With that bit refactored, I don't have a solid reason to advocate adding an option to deal with it, since I incur no extra network overhead. :)

**Comment by jvsteiner** [comment]
It looks like the `From` field is an alias of `string` - I don't think it encodes enough information to `Connect` back to the source - is that true, or have I missed something?  If not, I still need to include some data about the multiaddress in my application code in order to facilitate discovery.  That's ok, of course, but flagging that for this type of use, having just the peer ID as `From` in the `Message` isn't _everything_ one might want.

**Comment by Stebalien** [comment]
>  I don't think it encodes enough information to Connect back to the source - is that true, or have I missed something?

It should be the peer ID (stored as a string for performance reasons because go is weird that way).

You really shouldn't be using a multiaddr. The idea behind peer IDs is that the peer ID identifies the peer while the multiaddr just tells you how to reach the peer (peers have multiple and they change all the time). If you want to connect to a peer given a peer ID, libp2p will lookup the peer ID in the DHT (where peers publish their current multiaddrs).

**Comment by jvsteiner** [comment]
hmm, `host.Connect` receives a context, and a `peerstore.PeerInfo` which consists of an ID and a []multiaddr.  If I remove the multiaddr, my code doesn't work any more.  I also can't work out how it would connect to any DHT in the first place.  I confess I'm confused :)

**Comment by Stebalien** [comment]
Ah. I forgot, you're using the basic host (doesn't contain any routing logic (DHT stuff)). Unfortunately, I don't know of any good examples that use a routed host off the top of my head (go-ipfs does this but the setup is not simple).

In terms of discovery, what do you need out of "connecting back"? Do you just want to increase the number of pubsub peers? @vyzo is working on a next-gen protocol that'll have a special control message for that.

**Comment by jvsteiner** [comment]
"connect back" was a poor choice of words.  I meant currently in my code, the the peer receives `PeerInfo` for someone who shares interest in some topic, and then Connects to them at that address/ID.

**Comment by Stebalien** [comment]
>  I meant currently in my code, the the peer receives PeerInfo for someone who shares interest in some topic, and then Connects to them using that information.

Got it. I think the next version of pubsub will solve this for you.

However, routed hosts are generally useful and not as painful to construct as I had thought. You'll want to use `github.com/libp2p/go-libp2p/p2p/host/routed` for that. Construct the `Host` as usual (with the libp2p constructor), then construct a DHT *client* (`github.conm/libp2p/go-libp2p-kad-dht`), and finally construct the routed host. You *could* construct a full DHT node (not just a client) but I'd use a client-only config for now.

Here's a sketch. If something doesn't work, just ask. This isn't yet a full-blown example.

```go

import (
	"context"

	rhost "github.com/libp2p/go-libp2p/p2p/host/routed"
	libp2p "github.com/libp2p/go-libp2p"
	dht "github.com/libp2p/go-libp2p-kad-dht"
	dsync "github.com/ipfs/go-datastore/sync"
	ds "github.com/ipfs/go-datastore"
)

// ....

ctx, shutdown := context.WithCancel(context.Background())

/* ... your libp2p setup code ... */

// Finish by constructing the basic, non-routed host)
basicHost, err := libp2p.New(ctx, opts...)

// Construct a datastore (needed by the DHT). This is just a simple, in-memory thread-safe datastore.
dstore := dsync.MutexWrap(ds.NewMapDatastore())

// Make the DHT
dht := dht.NewDHT(ctx, basicHost, dstore)

// Make the routed host
host := rhost.Wrap(host, dht)
```

If you have a chance and time to make a PR, I'd love a full-blown example (like the echo example but with a routed host).

**Comment by jvsteiner** [comment]
Will give it a try, and happy to contribute a working example if I'm successful. I actually gave it a try already based on the ipfs setup, I managed to distill it down pretty well, but landed in some troubles with gx imports. This is a different approach, so let's see what happens! Thanks!

**Comment by Stebalien** [comment]
I usually use the normal go imports and then run `gx import package...` to import it into the `package.json`. I only rewrite the actual imports right before building (using `gx-go rw`).

We only leave `go-ipfs` in the "rewritten" state simply to avoid having to explain to users why their `go get github.com/ipfs/go-ipfs/cmds/ipfs` command failed with broken dependencies.

**Comment by jvsteiner** [comment]
I'm going to close this issue, but the purpose has drifted too much - will open a different issue if need be.
